# Generated by Django 3.0.8 on 2020-07-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='sku_code',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
